<?php

return [
    'slug' => 'cantilan',
    'name' => 'Cantilan Campus',
    'label' => 'College of Technological Education',
    'location' => 'Pag-antayan, Cantilan, Surigao del Sur, 8317',
    'email' => 'cantilan@nemsu.edu.ph',
    'headline' => 'NEMSU-Cantilan Campus advances technological education, professional training, and quality instruction in the Caraga Region.',
    'overview' => <<<'TEXT'
North Eastern Mindanao State University (NEMSU) – Cantilan Campus serves as the University’s designated College of Technological Education and is recognized as one of the leading state university campuses in the Caraga Region. Strategically located along the Pacific coast in Cantilan, Surigao del Sur, the campus is committed to delivering excellence in technological education, professional training, and quality instruction.

NEMSU–Cantilan produces competent, skilled, and industry-ready graduates in the fields of technology, engineering, criminology, education, and various vocational and technical disciplines. Through its strong culture of research, extension, and innovation, the campus continues to make significant contributions to regional growth and community development.

The campus is distinguished by its robust technology-driven and skills-based academic programs, modern laboratory facilities, and experiential learning environment that enhance students’ practical competencies and professional preparedness. NEMSU–Cantilan has consistently demonstrated outstanding performance in licensure examinations, particularly in Criminology, where it has produced board topnotchers and earned recognition as one of the top-performing institutions in the region.

In addition, the campus has shown commendable results in the Licensure Examination for Teachers (LET) and the Registered Master Electrician Licensure Examination, reflecting the quality, rigor, and relevance of its academic and technical programs.

Guided by its commitment to academic excellence, quality assurance, innovation, and community engagement, NEMSU–Cantilan Campus continues to strengthen its reputation as a dynamic and forward-looking institution. It remains steadfast in its mission to develop globally competitive, socially responsible, and service-oriented professionals equipped to meet the demands of an ever-evolving world.
TEXT,
    'highlights' => ['Technological education', 'Licensure examination excellence', 'Research, extension, and innovation'],
    'director' => 'Juancho A. Intano, PhD',
    'directorRole' => 'Professor V / Campus Director',
    'directorEmail' => 'nemsucantilan.cdoffice@gmail.com',
    'directorPhone' => '0907 867 0913',
    'focus' => 'Technology-driven and skills-based education',
    'facilities' => [
        'Old Science Building',
        'Science Building',
        'DIT Building',
        'Autocare Shop',
        'Automotive Building',
        'Mechanical Building',
        'Electrical and Electronics Building',
        'DGTT Building',
        'DBM Building 1',
        'DBM Building 2',
        'DCS Building',
        'CCJE Building',
        'Culture of Arts Gymnasium',
        'NSTP Building',
        'Research Development and Extension Building',
        'Makeshift Classroom',
        'Internet Laboratory',
        'Science and Physics Laboratory',
        'Technology and Economic Building (unusable)',
        'IGP Building 1',
        'IGP Building 2',
        'IGP Building 3',
        'Apartelle Building',
        'Mini Hotel Building',
        'New Hotel Building',
        'Old Dormitory',
        'Female Dormitory',
        'Male Dormitory',
        'RFID Building',
        'AVC Building',
        'Conference Hall Building (unusable)',
        'Library Building',
        'Administrative Office Building',
        'Alumni Building',
        'Motorpol',
        'Fish Dryer Building',
        'Coop Building',
    ],
    'facilityGallery' => [
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/old-science-building-1.webp',
            'alt' => 'Exterior of the Old Science Building',
            'title' => 'Old Science Building',
            'category' => 'Academic',
            'featured' => true,
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/old-science-building-2.webp',
            'alt' => 'Walkway of the Old Science Building',
            'title' => 'Old Science Building',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/science-building.webp',
            'alt' => 'Aerial view of the Science Building',
            'title' => 'Science Building',
            'category' => 'Academic',
            'wide' => true,
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/dit-building.webp',
            'alt' => 'Exterior of the DIT Building',
            'title' => 'DIT Building',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/autocare-shop.webp',
            'alt' => 'Exterior of the Autocare Shop',
            'title' => 'Autocare Shop',
            'category' => 'Technical Training',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/automotive-building.webp',
            'alt' => 'Exterior of the Automotive Building',
            'title' => 'Automotive Building',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/mechanical-building.webp',
            'alt' => 'Exterior of the Mechanical Building',
            'title' => 'Mechanical Building',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/electrical-electronics-building.webp',
            'alt' => 'Exterior of the Electrical and Electronics Building',
            'title' => 'Electrical and Electronics Building',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/dgtt-building-1.webp',
            'alt' => 'First exterior view of the DGTT Building',
            'title' => 'DGTT Building',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/dgtt-building-2.webp',
            'alt' => 'Second exterior view of the DGTT Building',
            'title' => 'DGTT Building',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/dbm-building-1.webp',
            'alt' => 'Exterior of DBM Building 1',
            'title' => 'DBM Building 1',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/dbm-building-2.webp',
            'alt' => 'Exterior of DBM Building 2',
            'title' => 'DBM Building 2',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/dcs-building.webp',
            'alt' => 'Exterior of the DCS Building',
            'title' => 'DCS Building',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/ccje-building.webp',
            'alt' => 'Exterior of the CCJE Building',
            'title' => 'CCJE Building',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/culture-of-arts-gymnasium.webp',
            'alt' => 'Aerial view of the Culture of Arts Gymnasium',
            'title' => 'Culture of Arts Gymnasium',
            'category' => 'Sports and Events',
            'wide' => true,
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/nstp-building.webp',
            'alt' => 'Exterior of the NSTP Building',
            'title' => 'NSTP Building',
            'category' => 'Community Service',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/research-development-extension-building.webp',
            'alt' => 'Exterior of the Research Development and Extension Building',
            'title' => 'Research Development and Extension Building',
            'category' => 'Research and Extension',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/makeshift-classroom-1.webp',
            'alt' => 'First exterior view of a makeshift classroom',
            'title' => 'Makeshift Classroom',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/makeshift-classroom-2.webp',
            'alt' => 'Second exterior view of a makeshift classroom',
            'title' => 'Makeshift Classroom',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/internet-laboratory.webp',
            'alt' => 'Exterior of the Internet Laboratory',
            'title' => 'Internet Laboratory',
            'category' => 'Technology',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/science-physics-laboratory.webp',
            'alt' => 'Exterior of the Science and Physics Laboratory',
            'title' => 'Science and Physics Laboratory',
            'category' => 'Academic',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/igp-building-1.webp',
            'alt' => 'Exterior of IGP Building 1',
            'title' => 'IGP Building 1',
            'category' => 'Income Generation',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/igp-building-2.webp',
            'alt' => 'Exterior of IGP Building 2',
            'title' => 'IGP Building 2',
            'category' => 'Income Generation',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/igp-building-3.webp',
            'alt' => 'Exterior of IGP Building 3',
            'title' => 'IGP Building 3',
            'category' => 'Income Generation',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/apartelle-building-1.webp',
            'alt' => 'First exterior view of the Apartelle Building',
            'title' => 'Apartelle Building',
            'category' => 'Income Generation',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/apartelle-building-2.webp',
            'alt' => 'Second exterior view of the Apartelle Building',
            'title' => 'Apartelle Building',
            'category' => 'Income Generation',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/mini-hotel-building.webp',
            'alt' => 'Exterior of the Mini Hotel Building',
            'title' => 'Mini Hotel Building',
            'category' => 'Income Generation',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/new-hotel-building.webp',
            'alt' => 'Exterior of the New Hotel Building',
            'title' => 'New Hotel Building',
            'category' => 'Income Generation',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/old-dormitory.webp',
            'alt' => 'Exterior of the Old Dormitory',
            'title' => 'Old Dormitory',
            'category' => 'Student Housing',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/female-dormitory.webp',
            'alt' => 'Exterior of the Female Dormitory',
            'title' => 'Female Dormitory',
            'category' => 'Student Housing',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/male-dormitory.webp',
            'alt' => 'Exterior of the Male Dormitory',
            'title' => 'Male Dormitory',
            'category' => 'Student Housing',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/rfid-building.webp',
            'alt' => 'Exterior of the RFID Building',
            'title' => 'RFID Building',
            'category' => 'Student Services',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/avc-building.webp',
            'alt' => 'Exterior of the AVC Building',
            'title' => 'AVC Building',
            'category' => 'Learning Support',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/library-building.webp',
            'alt' => 'Exterior of the Library Building',
            'title' => 'Library Building',
            'category' => 'Library',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/administrative-office-building.webp',
            'alt' => 'Exterior of the Administrative Office Building',
            'title' => 'Administrative Office Building',
            'category' => 'Administration',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/alumni-building.webp',
            'alt' => 'Exterior of the Alumni Building',
            'title' => 'Alumni Building',
            'category' => 'Alumni Services',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/motorpol.webp',
            'alt' => 'Exterior of the Motorpol facility',
            'title' => 'Motorpol',
            'category' => 'Income Generation',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/fish-dryer-building.webp',
            'alt' => 'Exterior of the Fish Dryer Building',
            'title' => 'Fish Dryer Building',
            'category' => 'Income Generation',
        ],
        [
            'image' => '/images/campuses/cantilan/facilities/gallery/coop-building.webp',
            'alt' => 'Exterior of the Coop Building',
            'title' => 'Coop Building',
            'category' => 'Income Generation',
        ],
    ],
    'programs' => [
        [
            'college' => 'Graduate School',
            'offerings' => [
                'Master in Teaching Technology Education (MTTE) major in Architectural Drafting Technology',
                'Master in Teaching Technology Education (MTTE) major in Automotive Technology',
                'Master in Teaching Technology Education (MTTE) major in Civil Technology',
                'Master in Teaching Technology Education (MTTE) major in Electrical Technology',
                'Master in Teaching Technology Education (MTTE) major in Food Technology',
                'Master in Teaching Technology Education (MTTE) major in Garments Technology',
            ],
        ],
        [
            'college' => 'College of Teacher Education',
            'offerings' => [
                'Bachelor of Secondary Education (BSEd) major in English',
                'Bachelor of Secondary Education (BSEd) major in Filipino',
                'Bachelor of Secondary Education (BSEd) major in Mathematics',
                'Bachelor of Secondary Education (BSEd) major in Science',
                'Bachelor of Technology and Livelihood Education (BTLEd) major in Home Economics',
                'Bachelor of Technical-Vocational Teacher Education (BTVTEd) major in Automotive Technology',
                'Bachelor of Technical-Vocational Teacher Education (BTVTEd) major in Electrical Technology',
                'Bachelor of Technical-Vocational Teacher Education (BTVTEd) major in Food & Services Management',
                'Bachelor of Technical-Vocational Teacher Education (BTVTEd) major in Garments Fashion & Design',
            ],
        ],
        [
            'college' => 'College of Criminal Justice Education',
            'offerings' => [
                'Bachelor of Science in Criminology (BSCrim.)',
            ],
        ],
        [
            'college' => 'College of Business and Management',
            'offerings' => [
                'Bachelor of Science in Business Administration (BSBA) major in Financial Management',
                'Bachelor of Science in Business Administration (BSBA) major in Human Resource Management',
                'Bachelor of Science in Hospitality Management (BSHM)',
                'Bachelor of Science in Tourism Management (BSTM)',
            ],
        ],
        [
            'college' => 'College of Information Technology Education',
            'offerings' => [
                'Bachelor of Science in Computer Engineering (BSCpE)',
                'Bachelor of Science in Computer Science (BSCS)',
                'Bachelor of Science in Information Technology (BS Info. Tech.)',
            ],
        ],
        [
            'college' => 'College of Engineering and Technology',
            'offerings' => [
                'Bachelor of Industrial Technology (BIndTech) major in Architectural Drafting Technology',
                'Bachelor of Industrial Technology (BIndTech) major in Automotive Technology',
                'Bachelor of Industrial Technology (BIndTech) major in Computer Technology',
                'Bachelor of Industrial Technology (BIndTech) major in Electrical Technology',
                'Bachelor of Industrial Technology (BIndTech) major in Electronics Technology',
                'Bachelor of Industrial Technology (BIndTech) major in Mechanical Technology',
                'Bachelor of Industrial Technology (BIndTech) major in Culinary Technology',
                'Bachelor of Industrial Technology (BIndTech) major in Apparel and Fashion Technology',
            ],
        ],
    ],
];
